{"name": "test_login_failed[case1]", "status": "passed", "attachments": [{"name": "stderr", "source": "89a18a89-ab93-4f46-8064-37cf93cad32d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误', 'user': 'helloworld', 'passwd': 'rabbit', 'check': '账号或密码不正确'}"}], "start": 1674741124152, "stop": 1674741124960, "uuid": "0a722f31-b029-4de4-b1e6-e85d756c501b", "historyId": "6d1f31bc7a689d732c0569e1009fbcbf", "testCaseId": "a30a453503605050407c31ba0e444078", "fullName": "testcase.test_user_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "linjie"}, {"name": "thread", "value": "6844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_user_login"}]}